### PR TITLE
Add GitHub actions update file and add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by JamyGolden**
**Bring screenshots into this repo so it's not reliant on the old repo**
I've also detached this repo from chris' old repo. TIL creating a PR on a fork is not easy :sweat_smile: 

**Remove Makefile since GitHub actions now builds coloschemes weekly**
CONTRIBUTING.md includes instructions on how to do manual local building, but it's not needed to be checked into the repo since the github action takes care of this now.

**Update readme formatting**
It's just following how the other readmes are, having the links at the bottom to clean up the file a bit and then line breaks at 72 chars.

**Add CONTRIBUTING.md**
This is basically a copy of the contributing.md file on the other repos, except there are references to this repo and in that case it includes `base16-iterm2`.

### CODE REVIEW

**Review by martinlindhe — APPROVED** [review]

**Comment by martinlindhe** [comment]
> Merging is blocked
> The base branch requires all commits to be signed. Learn more about signing commits. 

Ok, I don't even have git signing set-up myself yet but I do think its about time ;-)

**Comment by JamyGolden** [comment]
If you have issues with setting it up I can disable the requirement on repos you're involved with until you've gotten it set up (so there isn't a time pressure to do it)

**Comment by JamyGolden** [comment]
Actually I'll just disable it until you tell me that you've got commit signing enabled.

**Comment by martinlindhe** [comment]
@JamyGolden Thanks. I put up a post-it reminder on my desk. :-)

**Pull request merged**
